# Generated by Django 5.1.5 on 2025-02-28 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='Bookings.bookings'),
        ),
    ]
