# Generated by Django 5.1.5 on 2025-02-03 09:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Art Exhibitions', 'Art Exhibitions'), ('Cultural Festivals', 'Cultural Festivals'), ('Theater Plays', 'Theater Plays'), ('Dance Performances', 'Dance Performances'), ('Food Festivals', 'Food Festivals'), ('Wine Tastings', 'Wine Tastings'), ('Cooking Classes', 'Cooking Classe'), ('Beer Festivals', 'Beer Festivals'), ('Marathons', 'Marathons'), ('Yoga Sessions', 'Yoga Sessions'), ('Fitness Workshops', 'Fitness Workshops'), ('Sporting Events', 'Sporting Events'), ('Conferences', 'Conferences'), ('Seminars', 'Seminars'), ('Network Events', 'Networking Events'), ('Family-Friendly Events', 'Family Friendly Events'), ("Children's Workshops", 'Children Workshops'), ('Kid-Friendly Shows', 'Kid Friendly Shows'), ('Educational Activities', 'Educational Activites'), ('Tech Conferences', 'Tech Conferences'), ('Hackathons', 'Hackathons'), ('Startup Events', 'Startup Events'), ('Gadget Expos', 'Gadget Expos'), ('Start-up Comedy', 'Start Up Comedy'), ('Improve Nights', 'Improve Nights'), ('Comedy Festivals', 'Comedy Festivals'), ('Magic Shows', 'Magic Shows'), ('Fundraising Events', 'Fundraising Events'), ('Charity Galas', 'Charity Galas'), ('Benefit Concerts', 'Benefit Concerts'), ('Auctions & Fundraisers', 'Auctions Fundraisers'), ('Lectures & Talks', 'Lectures Talks'), ('Workshops', 'Workshops'), ('Educational Seminars', 'Educational Seminars'), ('Skill-Building Sessions', 'Skill Building Sessions'), ('City Tours', 'City Tours'), ('Adventure Travel', 'Adventure Travel'), ('Cultural Experiences', 'Cultural Experiences'), ('Cruise Vacations', 'Cruise Vacations')], max_length=200)),
                ('eventType', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(related_name='eventbooked', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventWaitingList', to='Events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userWaitingList', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
