# Generated by Django 5.1.5 on 2025-02-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
