# Generated by Django 5.1.5 on 2025-02-04 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorited',
            field=models.ManyToManyField(related_name='FavoriteEvent', to=settings.AUTH_USER_MODEL),
        ),
    ]
