# Generated by Django 5.1.5 on 2025-01-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification_delete_onetimepasscode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aboutme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relationship_status',
        ),
    ]
