# Generated by Django 5.1.5 on 2025-02-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
